spring:
  data:
    mongodb:
      uri: mongodb+srv://satyam:u3eshVEIoYh3sWTK@cluster0.8z7xq.mongodb.net/sample?retryWrites=true&w=majority
      database: sample

  output:
    ansi:
      enabled: ALWAYS

  cache:
    jcache:
      config: classpath:ehcache.xml

logging:
  level:
    root: INFO
    com:
      w2s: DEBUG


